---
default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: trailing-whitespace
      - id: double-quote-string-fixer
      - id: end-of-file-fixer

  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.15.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
      - id: markdownlint
